### ISSUE TITLE
Add support for MQTT Client ID and controller name

### ISSUE THREAD

**Issue by sarreck** [SuperHouse/LSC#14]
Add support for MQTT Client ID and Controller name in MQTT path

**Comment by sumnerboy12** [comment]
This has been implemented in #15. You can now optionally specify your own MQTT client id, or leave it blank to fall back to `LSC-XXXXXX` where `XXXXXX` is the last 6 digits of the MAC address.

**Comment by sumnerboy12** [comment]
@sarreck can you check that #15 implements what you want? If so can you close this issue.

**Comment by sarreck** [comment]
Thanks, good to close.
