### ISSUE TITLE
Auto discover MCP23017

### ISSUE THREAD

**Issue by jonoxer** [SuperHouse/LSC#2]
Suggestion by Austin: scan I2C at startup and auto configure for number of input ports.

**Comment by austinscreations** [comment]
could also be a way of detecting a failure, / outputting a warning to mqtt
glad you like the suggestion.
EDIT: was trying to think how you may add a check for knowing how many buttons are supposed to attached to the module...
something i do on my devices is that i have a standard topic that all my devices will output "connected - %device name%" to. you could add something like that but also add the number of buttons / i2c devices detected. so if you were using say node red you can now run a check for how many are supposed to be there. while I don't imagine you'd have many failures it could still be useful in say a power outage or a storm with lightning.

**Comment by Sausages69** [comment]
Great idea :)

**Comment by jonoxer** [comment]
This has been implemented by @sumnerboy12 using a scan starting at the base address, and ending at the first gap. This meets our short-term needs, but ultimately this needs to scan the entire range and skip any addresses that don't reply. The reason is that the control buttons on the OLED front panel are also on an MCP23017 but separate to the rest of the inputs, and it's always at the highest address. It will never be discovered if the scan stops at the first gap.

I'm leaving this issue open for now as a reminder for the future.

**Comment by sumnerboy12** [comment]
See https://github.com/SuperHouse/LSC/pull/10 for further work on this.

**Comment by sumnerboy12** [comment]
The code should now detect the OLED input button events and report them to MQTT. @jonoxer can you please test this on your Mega?

**Comment by sumnerboy12** [comment]
This should be complete once #16 is merged.

**Comment by sumnerboy12** [comment]
@jonoxer I think this can be closed now - the latest version supports I2C scanning properly.
